version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/homelab_dashboard
      - SESSION_SECRET=${SESSION_SECRET:-defaultsecretkey}
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads  # Persist any uploads

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=homelab_dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: