version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homelab-dashboard
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PROXMOX_HOST=${PROXMOX_HOST}
      - PROXMOX_USER=${PROXMOX_USER}
      - PROXMOX_TOKEN_NAME=${PROXMOX_TOKEN_NAME}
      - PROXMOX_TOKEN_VALUE=${PROXMOX_TOKEN_VALUE}
      - DOCKER_HOST=${DOCKER_HOST}
      - DOCKER_PORT=${DOCKER_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
    networks:
      - homelab-network

networks:
  homelab-network:
    external: true