version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://homelab_user:homelab_password@your-db-host:5432/homelab_dashboard}
      - SESSION_SECRET=${SESSION_SECRET:-defaultsecretkey}
    volumes:
      - homelab_uploads:/app/uploads

volumes:
  homelab_uploads: