name: Deploy to Homelab

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy with Docker Compose
        run: |
          cd $GITHUB_WORKSPACE
          docker-compose up -d --build