name: Deploy to Homelab

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env file
        run: |
          # Create .env file using a very simple approach
          rm -f .env
          touch .env
          printf "PROXMOX_HOST=%s\n" "${{ secrets.PROXMOX_HOST }}" >> .env
          printf "PROXMOX_USER=%s\n" "${{ secrets.PROXMOX_USER }}" >> .env
          printf "PROXMOX_TOKEN_NAME=%s\n" "${{ secrets.PROXMOX_TOKEN_NAME }}" >> .env
          printf "PROXMOX_TOKEN_VALUE=%s\n" "${{ secrets.PROXMOX_TOKEN_VALUE }}" >> .env
          printf "DOCKER_HOST=%s\n" "${{ secrets.DOCKER_HOST }}" >> .env
          printf "DOCKER_PORT=%s\n" "${{ secrets.DOCKER_PORT }}" >> .env
          printf "DATABASE_URL=%s\n" "${{ secrets.DATABASE_URL }}" >> .env
          printf "GITHUB_TOKEN=%s\n" "${{ secrets.GITHUB_TOKEN }}" >> .env
          printf "FLASK_ENV=production\n" >> .env
          printf "SECRET_KEY=%s\n" "${{ secrets.SECRET_KEY }}" >> .env
          printf "SESSION_SECRET=%s\n" "${{ secrets.SESSION_SECRET }}" >> .env
          
          echo "Created .env file:"
          cat .env

      - name: Copy project to server
        run: |
          # Add server to known hosts
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOMELAB_HOST }} >> ~/.ssh/known_hosts
          
          # Create homelab directory if it doesn't exist
          ssh ${{ secrets.HOMELAB_USER }}@${{ secrets.HOMELAB_HOST }} "mkdir -p ~/homelab-dashboard"
          
          # Copy project files to server
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'venv' \
            --exclude '__pycache__' \
            --exclude '*.pyc' \
            . ${{ secrets.HOMELAB_USER }}@${{ secrets.HOMELAB_HOST }}:~/homelab-dashboard/

      - name: Update Portainer stack
        run: |
          # Install jq
          sudo apt-get update && sudo apt-get install -y jq curl
          
          # Execute the update script
          bash .github/scripts/update-portainer.sh \
            "${{ secrets.PORTAINER_URL }}" \
            "${{ secrets.PORTAINER_API_KEY }}" \
            "homelab-dashboard" \
            "${{ secrets.HOMELAB_USER }}@${{ secrets.HOMELAB_HOST }}" \
            "~/homelab-dashboard"