name: Deploy to Homelab

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env file
        run: |
          # Create .env file more safely
          echo "# Proxmox configuration" > .env
          echo "PROXMOX_HOST=${{ secrets.PROXMOX_HOST }}" >> .env
          echo "PROXMOX_USER=${{ secrets.PROXMOX_USER }}" >> .env
          echo "PROXMOX_TOKEN_NAME=${{ secrets.PROXMOX_TOKEN_NAME }}" >> .env
          echo "PROXMOX_TOKEN_VALUE=${{ secrets.PROXMOX_TOKEN_VALUE }}" >> .env
          echo "" >> .env
          echo "# Docker configuration" >> .env
          echo "DOCKER_HOST=${{ secrets.DOCKER_HOST }}" >> .env
          echo "DOCKER_PORT=${{ secrets.DOCKER_PORT }}" >> .env
          echo "" >> .env
          echo "# Database configuration" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "" >> .env
          echo "# GitHub configuration (optional)" >> .env
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> .env
          echo "" >> .env
          echo "# Flask configuration" >> .env
          echo "FLASK_ENV=production" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env

      - name: Copy project to server
        run: |
          # Add server to known hosts
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOMELAB_HOST }} >> ~/.ssh/known_hosts
          
          # Create homelab directory if it doesn't exist
          ssh ${{ secrets.HOMELAB_USER }}@${{ secrets.HOMELAB_HOST }} "mkdir -p ~/homelab-dashboard"
          
          # Copy project files to server
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'venv' \
            --exclude '__pycache__' \
            --exclude '*.pyc' \
            . ${{ secrets.HOMELAB_USER }}@${{ secrets.HOMELAB_HOST }}:~/homelab-dashboard/

      - name: Update Portainer stack
        run: |
          # Install jq
          sudo apt-get update && sudo apt-get install -y jq curl
          
          # Execute the update script
          bash .github/scripts/update-portainer.sh \
            "${{ secrets.PORTAINER_URL }}" \
            "${{ secrets.PORTAINER_API_KEY }}" \
            "homelab-dashboard" \
            "${{ secrets.HOMELAB_USER }}@${{ secrets.HOMELAB_HOST }}" \
            "~/homelab-dashboard"