name: Deploy to Homelab

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env file (using static file)
        run: |
          # Use a static script to create the .env file to bypass any shell issues
          bash .github/static-env-creator.sh
          
          echo "Created static .env file for testing."

      - name: Copy project to server
        run: |
          # Add server to known hosts
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOMELAB_HOST }} >> ~/.ssh/known_hosts
          
          # Create homelab directory if it doesn't exist
          ssh ${{ secrets.HOMELAB_USER }}@${{ secrets.HOMELAB_HOST }} "mkdir -p ~/homelab-dashboard"
          
          # Copy project files to server
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'venv' \
            --exclude '__pycache__' \
            --exclude '*.pyc' \
            . ${{ secrets.HOMELAB_USER }}@${{ secrets.HOMELAB_HOST }}:~/homelab-dashboard/

      - name: Update Portainer stack
        run: |
          # Install jq
          sudo apt-get update && sudo apt-get install -y jq curl
          
          # Execute the update script
          bash .github/scripts/update-portainer.sh \
            "${{ secrets.PORTAINER_URL }}" \
            "${{ secrets.PORTAINER_API_KEY }}" \
            "homelab-dashboard" \
            "${{ secrets.HOMELAB_USER }}@${{ secrets.HOMELAB_HOST }}" \
            "~/homelab-dashboard"